### PR TITLE
Update cheat_core_player.lua

### PR DESCRIPTION
**Pull request by aleksey-orekhov**
Add all treasures to cheat_teleport_to command.

### CODE REVIEW

**Comment by pryans** [comment]
Looks like this was added in another merge. See command cheat_tp_tr

**Comment by aleksey-orekhov** [comment]
Hi @pryans,

Makes sense. I have mixed feelings about the way things turned out.

I'm glad the feature is in, but the commit that wound up adding a similar feature copied from this PR without giving attribution. I know that's the case because this PR was created ~6 months earlier and the x,y,z coordinates are identical. 

https://github.com/pryans/kcd-cheat/commit/586c4a9b309c5caaba9d50182af9b3f31fb386f5

When I originally found these coordinates, I tried to land in a spot where you could see the treasure from, not always directly on top of the treasure, because sometimes there were bandits. I also chose a 'z' coordinate slightly above the ground to avoid clipping, but not the same distance every time. It is nearly impossible that someone would arrive at the same coordinates just by chance.

I understand how it happened though, and it wasn't your fault. You have not visited this repo in a while, and when you did, you merged the most recent pull requests first. Then you noticed the merge conflict after those were in. Thanks again for making this fantastic library that greatly enhanced my enjoyment of KCD!

As for @wilecoyote , I'm just going to assume that at least in this case, they were fans of the expression: "Imitation is the sincerest form of flattery". Thanks also for your contributions and for trying to make KCD more fun for everyone! (Just please give attribution next time!)

**Comment by wilecoyote** [comment]
I mentioned in the readme,md of my fork, that i brought the best additions and changes of all 12 forks together. In the course of the pull request, however, the file got deleted. I was never concerned enriching me with the work of other authors (If that had been my intention, I would not have started a pull request.), but to fix some reported issues and improving the mod we all love. Why should someone fork if he isn't ready to provide his changes via pull request for others? I only waited with the pull request until yesterday because I wanted to make sure that everything on my list of improvements and fixes was implemented and works as intended. I am sorry that the changes from other authors are not clear to everyone, but maybe Pryans can mention the names in his sticky (Magicgonads, Aleksey-Orekhov, Joewalabel and Lernos)

**Comment by aleksey-orekhov** [comment]
@wilecoyote 

hahaha, I agree that none of us are going to get rich by doing this any time soon. I don't need a mention on the sticky. 

I saw your [profile](https://www.nexusmods.com/kingdomcomedeliverance/users/3428152) description on NexusMods, so I know that you care enough about content creators owning their work to delete your mods from that site. You don't think it is right that they want to take ownership of all your contributions to monetize them. I think that this is just a case of the shoe being on the other foot. (i.e. it appeared that you were attempting to take ownership of other people's contributions without their consent)

RE: Why people fork. I think they do it for all kinds of reasons and they may or may not want their work merged in. (In this case, I did want it merged in, hence the pull request). 

For next time it is usually better to contact the people who made the forks and ask them if it is ok to merge them in. I would either have said yes, or asked you if you could help get this PR in. Then, my first interaction with you would have left me thinking "What a great person!" instead of "Did they just copy 5 hours of my work and say that it is theirs? not cool!"

The thing is, you probably are a pretty great person. You must be. You just put in a lot of work to try and make the library better for everyone. Just please try to not trip over the little things next time:

1) Check if there is an existing PR before adding your own.
2) Try to contact the person who wrote the code you want to use, or at least mention them in the commit message.

You'll wind up making more friends, and the world will be a better place for it :)

**Comment by wilecoyote** [comment]
> I think that this is just a case of the shoe being on the other foot. (i.e. it appeared that you were attempting to take ownership of other people's contributions without their consent)

Quite apart from the fact that you should have proof of this claim, it is simply false and not true. I have never published or updated any mod without obtaining the author's permission or the permission settings on the mod page at Nexus allowed it by default. Luckily I have kept any conversation so that I can prove it if necessary. Apart from all the published updates, I have made many others and had them sent privately to the authors so that they can decide for themselves whether to use and publish them

If one doesn't want changes of a fork to be used, the fork should be set to private and not public. I never said or claimed that  all of the implemented changes were my work. I contributed my own ideas and brought some changes of other forks together, In some cases I added my personal interpratation of the addition/change because I had a smiliar idea or it didn't work as expected. I didn't start modding for fame, glory, or money, and certainly not to make virtual friends who would stab me in the back at the first opportunity.

**Comment by pryans** [comment]
If you want the original change to be included as well then send a working PR and I'll merge it. No reason both methods can't be included. I just didn't want to try and resolve the merge conflicts myself since I can't test anything.

**Comment by aleksey-orekhov** [comment]
@pryans Thanks! I'll do that!

@wilecoyote I'm happy to hear that this situation is unusual, and most likely a mixup. I did find the readme after you mentioned it, and you did try to credit a few of the authors.

RE:
> If one doesn't want changes of a fork to be used, the fork should be set to private and not public

I don't think the two of us are going to see eye to eye on this one. That's ok. We were both trying to do something good. We just disagree on the method. Legally and technically, I suspect you can do what you did. However, people really appreciate the effort you take to show them courtesy, especially when you are not legally required to do so.

RE:
> I didn't start modding for fame, glory, or money, and certainly not to make virtual friends who would stab me in the back at the first opportunity.

I'm sorry that someone treated you badly before. Hopefully you will be more lucky with the people you meet in the future!

**Comment by wilecoyote** [comment]
Oh my gosh! Don't make an elephant out of a mosquito. It's getting really ridiculous. You're acting like I stole a super important program from you and that's not the case. You added some places with coordinates to an existing command. No more and no less. If it's that important to you, I can remove it. Just let me know.

I will end this conversation at this point and consider carefully if I keep contributing or not.

**Comment by aleksey-orekhov** [comment]
Hi,

I just created https://github.com/pryans/kcd-cheat/pull/28  It now has a
bunch of bandit camps and some gardens in addition to the other locations.
I tested the cheat_teleport_to command at a bunch of locations (both old
and new) and it seems to work.

Sorry that it took a while and that it has a bunch of unrelated whitespace
changes, I think they happened as part of an autoformat.

**Pull request closed without merging**
